type SimSettings {
    cellSize:number,
    gridSize: number,
    timeStep: number,
    dissipation: number,
    viscosity: number,
    diffusion: number,
    iteration: number,
    blur: number,
    emissionRate: number,
    separation: number,
    emitterSize: number,
    color: number[],
    fluidColor: number[],
    attractorForce: number,
    attractorRadius: number,
    repulserForce: number,
    repulserRadius: number,
    addRepulser: () => void,
    addAttractor: () => void,
    clearAllObjects:() => void
  }